# Generated by Django 5.1.9 on 2025-08-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_phone_number_staffshift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffShift',
            new_name='Shift',
        ),
    ]
