# Generated by Django 5.1.9 on 2025-08-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.position'),
        ),
    ]
