# Generated by Django 5.1.9 on 2025-08-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staffprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
