# Generated by Django 5.1.9 on 2025-08-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_worklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='shift',
        ),
    ]
