# Generated by Django 5.1.9 on 2025-08-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_staffprofile_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='salary_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.RenameModel(
            old_name='WorkLog',
            new_name='AbsenceLog',
        ),
        migrations.CreateModel(
            name='SalaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('absence_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.absencelog')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile')),
            ],
        ),
    ]
