# Generated by Django 5.1.9 on 2025-08-05 18:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staffprofile_salary_per_hour_alter_shift_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarylog',
            name='absence_log',
        ),
        migrations.AddField(
            model_name='absencelog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='absencelog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarylog',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarylog',
            name='total_absent_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='salarylog',
            name='total_hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='salarylog',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absencelog',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absencelog',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.shift'),
        ),
        migrations.AlterField(
            model_name='absencelog',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='staff.staffprofile'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField()),
                ('is_substitute', models.BooleanField(default=False)),
                ('is_overtime', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='staff.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='staff.staffprofile')),
            ],
        ),
    ]
