# Generated by Django 5.1.9 on 2025-08-05 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_remove_salarylog_absence_log_absencelog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
