# Generated by Django 5.1.9 on 2025-08-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_salarylog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbsenceLog',
        ),
    ]
