# Generated by Django 5.1.9 on 2025-08-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_delete_absencelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='salary_per_hour',
            new_name='hourly_rate',
        ),
    ]
