# Generated by Django 5.1.9 on 2025-07-25 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientusage',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ingredientpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
