# Generated by Django 5.1.9 on 2025-07-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ingredientusage_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientusage',
            old_name='date',
            new_name='date_used',
        ),
    ]
