# Generated by Django 5.1.9 on 2025-07-29 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_date_ingredientusage_date_used'),
        ('menu', '0002_alter_customization_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientusage',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
    ]
