# Generated by Django 5.1.9 on 2025-07-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_ingredientusage_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock_level',
        ),
    ]
