# Generated by Django 5.1.9 on 2025-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_ingredientpurchase_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientusage',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
