# Generated by Django 5.1.9 on 2025-07-15 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_is_paid_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
