# Generated by Django 5.1.9 on 2025-07-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='seat',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
