# Generated by Django 5.1.9 on 2025-07-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_alter_table_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
